# This is a basic workflow to help you get started with Actions

name: npm-audit

# Controls when the action will run. 
on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm audit action
        uses: oke-py/npm-audit-action@v1.7.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: hidekuro
          dedupe_issues: true
